sudo: false

language: go

os:
  - linux
  - osx

addons:
  apt:
    update: true

go:
  - 1.13.x
  - 1.14.x
  - master
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - echo "before_install start"
  - df -h
  - pwd
  - uname -a
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
    fi
  - go version
  - go get

install:
  - echo "install start"
  - echo "install done"

before_script:
  - echo "before_script start"
  - go vet ./...
  - echo "before_script end"

script:
  - go build -a -v .
  - go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic ./...

after_script:
  - echo "after_script start"
  - echo "after_script done"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always
